### ISSUE TITLE
First line of of imported file throws "SyntaxError: invalid syntax" 

### ISSUE THREAD

**Issue by agh92** [pagekite/PyBreeder#2]
I succesfully used the tool to merge some files together and run them. But when I use the flagg `--compress` (everything else remains the same) I get an error:

> Traceback (most recent call last):
>   File "/tmp/jenkins5202313594849971078.sh", line 75, in <module>
>     exec __FILES[".SELF/automation/core/time_utils.py"] in m.__dict__
>   File "<string>", line 3
>     import datetime
>                    ^
> SyntaxError: invalid syntax

I dont know what this could be. I tried modifying the import statement and even make the import locally in the functions but the error remains with whatever the first line is. 

> Traceback (most recent call last):
>   File "/tmp/jenkins2249252542286121082.sh", line 74, in <module>
>     exec __FILES[".SELF/automation/core/time_utils.py"] in m.__dict__
>   File "<string>", line 1
>     def string_now():
>                      ^
> SyntaxError: invalid syntax

If I remove the flag `--compress` then it all works just fine.

Info: I´m using Python 2.6.6 and Linux

thanks in advance

**Comment by agh92** [comment]
I did some further testing and it happens with each one of the files that are imported but it just crashes with the first exec statement it finds. It alwasy shows syntax error in the first line. Some times at the end some times at the beginning. 

> Traceback (most recent call last):
>   File "/tmp/jenkins4655436272618925130.sh", line 70, in <module>
>     exec __FILES[".SELF/automation/core/log.py"] in m.__dict__
>   File "<string>", line 1
>     from automation.core.time_utils import string_now
>                                                      ^
> SyntaxError: invalid syntax

However I have some empty __init__.py that are imported the same way with as the other files and there is no problem with the exec statement for them.

I hope this helps
