### ISSUE TITLE
Test not working with python 3.8.2

### ISSUE THREAD

**Issue by mahesh557** [pagekite/PyBreeder#5]
Hi, Getting below error

```
$ python breeder.py test/testing/ test/__main__.py >big-snake.py
Traceback (most recent call last):
  File "breeder.py", line 258, in <module>
    print(breed(fn, (fn == args[-1]), gtk_images=gtk_images, compress=compress))
  File "breeder.py", line 210, in breed
    return breed_dir(fn, main,
  File "breeder.py", line 198, in breed_dir
    bred = breed(fn, ismain,
  File "breeder.py", line 217, in breed
    return breed_python(fn, main, gtk_images=gtk_images, compress=compress)
  File "breeder.py", line 108, in breed_python
    pre, lines, post = format_snake(fn, raw=main, compress=compress)
  File "breeder.py", line 99, in format_snake
    lines = [l.replace('\n', '')
  File "breeder.py", line 99, in <listcomp>
    lines = [l.replace('\n', '')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by pagekite** [comment]
Thank you for filing this! However, I think we are probably deprecating this tool (PyBreeder) and won't be fixing any more issues.

I recommend using [zipapp](https://docs.python.org/3/library/zipapp.html) instead, as it should be both more elegant and more performant.
